[package]
name = "muehlespiel"
version = "0.1.0"
edition = "2021"
authors = ["Simon Wazynski (M-Nr. 3659102)"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scan-rules = "0.2.0"
rand = "0.8.5"
fnv = "1.0.7"